# Generated by Django 2.1.15 on 2021-05-25 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ingredient_recipie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipie',
            new_name='Recipe',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
